# Generated by Django 3.0.2 on 2020-01-31 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_no',
            field=models.CharField(max_length=100, verbose_name='样板号'),
        ),
        migrations.AlterField(
            model_name='sample_os_avatar',
            name='sample',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='os_avatar', serialize=False, to='scm.Sample'),
        ),
    ]
