# Generated by Django 3.0.2 on 2020-02-01 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample_pics_factory',
            old_name='pic',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='sample_pics_factory',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_pics', to='scm.Sample'),
        ),
    ]
