# Generated by Django 3.0.7 on 2022-01-18 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='检查类别')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Check_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='检查项目')),
                ('number', models.IntegerField()),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('check_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Checkpoints', to='scm.Check_item')),
            ],
        ),
        migrations.CreateModel(
            name='Qc_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scm.Qc', verbose_name='质检人员')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkrecords', to='scm.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Check_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, choices=[('YZ', '严重'), ('CY', '次要')], max_length=50, verbose_name='严重等级')),
                ('ratio', models.CharField(max_length=50, verbose_name='比列')),
                ('file', models.ImageField(blank=True, upload_to='order/qc/')),
                ('Check_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scm.Check_point')),
                ('qc_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkrecords', to='scm.Qc_report')),
            ],
        ),
    ]
