# Generated by Django 3.0.4 on 2020-03-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_ship_qty',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='itemgroup_code',
            field=models.CharField(max_length=100, null=True, verbose_name='ITEM GROUP'),
        ),
        migrations.AddField(
            model_name='order',
            name='pgr_code',
            field=models.CharField(max_length=100, null=True, verbose_name='PGR'),
        ),
        migrations.AddField(
            model_name='order',
            name='season_code',
            field=models.CharField(max_length=100, null=True, verbose_name='SEASON'),
        ),
        migrations.AlterField(
            model_name='order',
            name='destination',
            field=models.CharField(blank=True, choices=[(None, '请选择'), ('AU', '澳洲'), ('NZ', '新西兰'), ('SG', '新加坡'), ('KR', '韩国')], max_length=50, verbose_name='目的地'),
        ),
    ]
