# Generated by Django 3.0.7 on 2020-06-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandiser',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
    ]
