# Generated by Django 3.0.2 on 2020-01-20 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='管理员')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='品牌')),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='设计师')),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='工厂')),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='财务')),
            ],
        ),
        migrations.CreateModel(
            name='Merchandiser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='跟单')),
            ],
        ),
        migrations.CreateModel(
            name='Merchandiser_Manager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='跟单主管')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='行政')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Qc',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='质检')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='船务')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='款式')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_qc',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_avatar', models.ImageField(blank=True, upload_to='samples/avatar/', verbose_name='原版头像')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='创建日期')),
                ('sample_no', models.PositiveIntegerField(verbose_name='样板号')),
                ('has_os_sample', models.BooleanField(verbose_name='是否有原版?')),
                ('parcel_date', models.DateField(blank=True, null=True, verbose_name='寄件日期')),
                ('qutation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='工厂报价')),
                ('qutation_form', models.ImageField(blank=True, upload_to='samples/qutation/', verbose_name='报价单')),
                ('os_pic', models.ImageField(blank=True, upload_to='samples/os_pics/', verbose_name='原版照片')),
                ('sample_pic', models.ImageField(blank=True, upload_to='samples/pics/', verbose_name='样板照片')),
                ('swatch_pic', models.ImageField(blank=True, upload_to='samples/swatch/', verbose_name='色卡')),
                ('alteration', models.TextField(blank=True, verbose_name='制版评语')),
                ('size_spec', models.FileField(blank=True, upload_to='samples/size_spec/', verbose_name='评语附件')),
                ('size_spec_factory', models.ImageField(blank=True, upload_to='samples/size_spec_factory/', verbose_name='样板尺寸表')),
                ('status', models.CharField(blank=True, choices=[('NEW', 'NEW'), ('COMPLETED', 'COMPLETED')], max_length=50, verbose_name='样板状态')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='scm.Brand', verbose_name='品牌')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='scm.Designer', verbose_name='设计师')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='scm.Factory', verbose_name='工厂')),
                ('merchandiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='scm.Merchandiser', verbose_name='跟单')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='scm.Style', verbose_name='款式')),
            ],
        ),
    ]
