# Generated by Django 3.0.4 on 2020-03-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0002_auto_20200320_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='actual_ship_qty',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='itemgroup_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ITEM GROUP'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pgr_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PGR'),
        ),
        migrations.AlterField(
            model_name='order',
            name='season_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SEASON'),
        ),
    ]
