# Generated by Django 3.0.7 on 2022-01-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0002_check_item_check_point_check_record_qc_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_point',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
    ]
