# Generated by Django 3.0.2 on 2020-02-01 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0002_auto_20200201_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample_quotation_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='sample/sample_quotation_form/')),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scm.Sample')),
            ],
        ),
        migrations.DeleteModel(
            name='Sample_qutation_form',
        ),
    ]
