# Generated by Django 3.0.2 on 2020-02-01 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0003_auto_20200201_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample_quotation_form',
            name='sample',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='scm.Sample'),
        ),
    ]
