# Generated by Django 3.0.7 on 2022-01-18 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0003_auto_20220118_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_point',
            name='check_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Checkpoints', to='scm.Check_item', verbose_name='检查类别'),
        ),
        migrations.AlterField(
            model_name='check_point',
            name='number',
            field=models.CharField(max_length=20, verbose_name='序号'),
        ),
    ]
