# Generated by Django 3.0.7 on 2020-06-09 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0003_auto_20200609_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='email',
        ),
        migrations.RemoveField(
            model_name='merchandiser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='merchandiser_manager',
            name='email',
        ),
        migrations.RemoveField(
            model_name='office',
            name='email',
        ),
        migrations.RemoveField(
            model_name='qc',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='email',
        ),
    ]
