# Generated by Django 3.0.2 on 2020-01-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0004_auto_20200122_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, upload_to='post/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='catagory',
            field=models.CharField(choices=[('通知', '通知'), ('手册', '手册')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='发布日期'),
        ),
    ]
