# Generated by Django 3.0.7 on 2020-06-10 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0004_auto_20200609_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='PHangingtape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='挂衣绳')),
            ],
        ),
        migrations.CreateModel(
            name='PPackingway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='包装要求')),
            ],
        ),
        migrations.CreateModel(
            name='PShippingsample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='船头板')),
            ],
        ),
        migrations.CreateModel(
            name='PSparebutton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='备用扣')),
            ],
        ),
        migrations.CreateModel(
            name='PWashinglabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='洗水唛')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='matchcolor',
            field=models.TextField(blank=True, verbose_name='配色要求'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, verbose_name='生产办评语'),
        ),
        migrations.AddField(
            model_name='order',
            name='PHangingtape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scm.PHangingtape', verbose_name='挂衣绳'),
        ),
        migrations.AddField(
            model_name='order',
            name='PPackingway',
            field=models.ManyToManyField(blank=True, null=True, to='scm.PPackingway', verbose_name='包装要求'),
        ),
        migrations.AddField(
            model_name='order',
            name='PShippingsample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scm.PShippingsample', verbose_name='船头板'),
        ),
        migrations.AddField(
            model_name='order',
            name='PSparebutton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scm.PSparebutton', verbose_name='备用扣'),
        ),
        migrations.AddField(
            model_name='order',
            name='PWashinglabel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scm.PWashinglabel', verbose_name='洗水唛'),
        ),
    ]
