# Generated by Django 3.0.2 on 2020-02-02 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0004_auto_20200201_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='scm.Style', verbose_name='款式'),
        ),
        migrations.AlterField(
            model_name='sample_size_spec_factory',
            name='sample',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sizespecf', to='scm.Sample'),
        ),
    ]
