# Generated by Django 3.0.7 on 2022-01-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0004_auto_20220118_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='qc_report',
            name='status',
            field=models.CharField(choices=[('NEW', '新建'), ('VIEWED', '已查阅')], default='NEW', max_length=100, verbose_name='状态'),
        ),
    ]
