# Generated by Django 3.0.7 on 2020-06-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0005_auto_20200610_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwashinglabel',
            name='description',
            field=models.CharField(max_length=400, verbose_name='洗水唛'),
        ),
    ]
