# Generated by Django 3.0.2 on 2020-01-23 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0005_auto_20200123_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, upload_to='post/', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='post',
            name='catagory',
            field=models.CharField(choices=[('通知', '通知'), ('手册', '手册')], max_length=100, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scm.Office', verbose_name='发布人'),
        ),
    ]
