# Generated by Django 3.0.7 on 2022-01-19 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0005_qc_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qc_report',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='质检人员'),
        ),
    ]
