# Generated by Django 3.0.7 on 2020-06-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0006_auto_20200610_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='PPackingway',
            new_name='PPackingways',
        ),
    ]
