# Generated by Django 3.0.7 on 2022-01-20 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0006_auto_20220119_0731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check_record',
            old_name='Check_point',
            new_name='check_point',
        ),
    ]
