# Generated by Django 3.0.2 on 2020-02-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0006_auto_20200202_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
    ]
