# Generated by Django 3.0.7 on 2022-01-20 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0007_auto_20220120_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_record',
            name='check_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scm.Check_item'),
            preserve_default=False,
        ),
    ]
