# Generated by Django 3.0.7 on 2022-01-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0009_auto_20220121_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_record',
            name='grade',
            field=models.CharField(blank=True, choices=[(None, '请选择'), ('YZ', '严重'), ('CY', '次要')], max_length=50, null=True, verbose_name='严重等级'),
        ),
        migrations.AlterField(
            model_name='check_record',
            name='ratio',
            field=models.CharField(max_length=50, null=True, verbose_name='比列'),
        ),
    ]
