# Generated by Django 3.0.7 on 2020-06-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0010_auto_20200612_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='PHangingtape',
            field=models.CharField(blank=True, default='无', max_length=100, null=True, verbose_name='挂衣绳'),
        ),
    ]
