# Generated by Django 3.0.7 on 2022-01-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0010_auto_20220121_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qc_report',
            name='status',
            field=models.CharField(choices=[('NEW', '新建'), ('FINISH', '完成')], default='NEW', max_length=100, verbose_name='状态'),
        ),
    ]
