# Generated by Django 3.0.7 on 2022-01-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0014_auto_20220124_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qc_report',
            name='status',
            field=models.CharField(choices=[('NEW', '新建'), ('FINISH', '完成'), ('SEND', '已发送')], default='NEW', max_length=100, verbose_name='状态'),
        ),
    ]
