# Generated by Django 3.0.7 on 2022-02-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0025_auto_20220209_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qc_report',
            name='ratio',
            field=models.CharField(max_length=50, verbose_name='抽查数量/件'),
        ),
    ]
