# Generated by Django 3.0.7 on 2022-03-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0029_order_production'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_bulk_fabric',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='order_production',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='order_shipping_sample',
            options={'ordering': ['-created_date']},
        ),
    ]
