# Generated by Django 3.0.7 on 2022-03-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0030_auto_20220301_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qc_report',
            options={'ordering': ['-created_date']},
        ),
    ]
