# Generated by Django 3.0.7 on 2022-08-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0033_auto_20220811_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='estimate_finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='预计完成日期'),
        ),
    ]
