# Generated by Django 3.0.7 on 2022-08-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0034_auto_20220811_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='estimate_finish_date',
        ),
    ]
