# Generated by Django 3.0.7 on 2022-08-11 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0036_sample_estimate_finish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='estimate_finish_date',
        ),
    ]
